### PR TITLE
Migrate to TypeScript and use React Hooks internally

### PR DESCRIPTION
**Pull request by kristof0425**
**Done**:
- [X] Migrated to TypeScript
- [X] Using new Hooks API
- [X] Rewrote tests not to include any implementation details
- [x] Edit `README.md`

### CODE REVIEW

**Comment by ljharb** [comment]
Note that this is a breaking change, not a minor, because it doesn't work in the same versions of React. It should be v4, not v3.2.

**Comment by kristof0425** [comment]
You are right @ljharb. Thanks for noticing me! 🙂 I’ll resolve it.

**Comment by ljharb** [comment]
My personal suggestion would be not to use hooks, precisely because it sharply limits who can use this package. That kind of choice is best made at an app level, not in a published package (same, for example, with using new Context)

**Comment by kristof0425** [comment]
@ljharb I'd like to thank you for helping to guide me. 🙇‍♂️

Regarding your last comment, ~I'm not convinced of not using the Hooks API~. Here are my reasons:
- For me, `react-with-breakpoints` has always been my "pet project" to try out and support the latest React APIs.
- I don't see a problem releasing a v4 update of the package, which requires to use a Hook API compatible React version. The potential user of `react-with-breakpoints` **can always choose** (thanks to semver) to use an older version of the lib (in our case, it's 3.1.1). In the README, I also planned to advise the users to use v3.x instead if they use earlier version of React.

What do you think of this approach?

**Comment by ljharb** [comment]
I think the minimum requirement is to support semver; certainly your proposal will *work*, but any new features you add to v4 but don’t backport to v3 immediately means they *cant* choose to use an older version of the lib.

If it’s your pet project and you’re not concerned with broad adoption and support, then your plan is fine.

**Pull request merged**
